import AppHeader from "./AppHeader";
import AppContent from "./AppContent";
import AppFooter from "./AppFooter";
import CardBox from "./CardBox";
import Hero from "./Hero";
import Team from "./Team";
import Support from "./Support";
import Success from "./Success";
import Client from "./Client";
import ClientCard from "./ClientCard";
import Faq from "./Faq";
import Service from "./Service";
export { AppContent, AppHeader, AppFooter, CardBox, Hero, Team, Support, Success, Client, ClientCard ,Faq,Service};
